siteConfig:
  lang: en
  title: cottage
  description: A humble homepage of sorts...
  # For the footer
  generatorUrl: https://saber.land
  generatorTitle: Static-site generator for Vue
  generatorName: Saber
  hostUrl: https://netlify.com
  hostTitle: Super-powers for static sites!
  hostName: Netlify
  # For the edit links
  repoLink: https://github.com/andreasvirkus/cottage
  # For RSS feed
  author: andreas virkus
  url: https://andreasvirkus.me
  email: write@andreasvirkus.me
  # For our service worker
  pwaFirstTimeInstallMessage: Ready for offline use ⚡️
  pwaUpdateFoundMessage: Loading content in the background...
  pwaUpdateReadyMessage: Fresh content is available!
  pwaUpdateButtonMessage: update
  pwaDismissMessage: dismiss

permalinks:
  page: /:slug
  post: /thoughts/:slug

# build:
  #extractCSS: true

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-search
  - resolve: saber-plugin-pwa
  - resolve: saber-plugin-google-analytics
    options:
      trackId: 'UA-99596348-1'
      anonymizeIp: true
  - resolve: saber-plugin-copy-code
    options:
      buttonStyle:
        border: 'none'
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
      rss2Feed: true
      jsonFeed: true
